### ISSUE TITLE
Using with protractor-cucumber-framework

### ISSUE THREAD

**Issue by odravison** [kozhevnikov/cucumber-pretty#1]
Hello, 

I have a issue with the pretty output log. I'm using protractor-cucumber-framework to run my tests and I don't know how configure cucumber-pretty in there.

My `cucumber.conf.js` file has this part of code.

```
cucumberOpts: {
        require: [
            '../javascript/e2e/steps/*.js',
        	'../javascript/e2e/hooks/geral.hook.js',
        	'../javascript/e2e/hooks/*.hook.js'
        	],
        tags: false,
        format: ['json:.tmp/results.json'],
        profile: false,
        'no-source': true
      },
```

I had try insert the cucumber-pretty inside of format: section, didn't work.

Someone has a idea to use cucumber-pretty side by side with protractor-cucumber-framework ?

Thanks in advanced.

**Comment by kozhevnikov** [comment]
I don't use Protractor myself and questions on how to add Cucumber formatters to it should probably go to protractor-cucumber-framework's maintainers but a quick code search shows that it is indeed cucumberOpts.format array. Could you post the config that didn't work?

https://github.com/search?l=JavaScript&q=protractor+cucumber-pretty&type=Code

**Comment by odravison** [comment]
I'm sorry about the late.
Sure, this is the config:

```
cucumberOpts: {
        require: [
            '../javascript/e2e/steps/*.js',
        	'../javascript/e2e/hooks/geral.hook.js',
        	'../javascript/e2e/hooks/*.hook.js'
        	],
        tags: false,
        format:  ['json:.tmp/results.json', '/node_modules/cucumber-pretty'],
        profile: false,
        'no-source': true
      },
```

**Comment by kozhevnikov** [comment]
Slash in `/node_modules` means it's an absolute path starting from the root which is very unlikely. Try relative path from current directory, either `node_modules` or `./node_modules`.

**Comment by odravison** [comment]
Sorry about this configuration, I just type "on the fly".

The path is absolutely OK, up in code has a part that I add a prefix and the path turns absolute and complete. I just forgot to type this.

I'll run and post here the error output.
