### ISSUE TITLE
Error TypeError: options.eventDataCollector.getTestCaseAttempt is not a function     at EventEmitter

### ISSUE THREAD

**Issue by davidquintard** [kozhevnikov/cucumber-pretty#12]
Hi there, 
I've got this error:

E/launcher - Error: TypeError: options.eventDataCollector.getTestCaseAttempt is not a function
    at EventEmitter.<anonymous> (/home/gfp/Application/current/ionic4/node_modules/cucumber-pretty/index.js:52:70)
    at EventEmitter.emit (events.js:208:15)
[11:47:16] E/launcher - Process exited with error code 100

````
cucumberOpts: {
    // require step definition files before executing features
    require: ['./e2e/steps/**/**/*.ts'],
    // <string[]> (expression) only execute the features or scenarios with tags matching the expression
    tags: [],
    // <boolean> fail if there are any undefined or pending steps
    strict: true,
    // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    format: [
      'node_modules/cucumber-pretty',
      'node_modules/cucumber-pretty:reports/summary.txt',
      'json:reports/summary.json'
    ],
    // <boolean> invoke formatters without executing steps
    dryRun: false,
    // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
    compiler: []
  },
````

**Comment by kozhevnikov** [comment]
What versions of `cucumber` and `cucumber-pretty` do you use?

For Cucumber.js versions 3 to 5 please use cucumber-pretty ^1.5.2
For Cucumber.js version 6 (latest) please use cucumber-pretty ^6.0.0 (latest)

**Comment by davidquintard** [comment]
I'm using cucumber 5.x.
I switch to cucumber-pretty ^1.5.2 and it works fine!
Thank you very much @kozhevnikov
