### ISSUE TITLE
Support cucumber-js 7

### ISSUE THREAD

**Issue by mattwynne** [kozhevnikov/cucumber-pretty#14]
I love this thing, thanks so much for making and maintaining it!

As of [cucumber-js 7](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#700-rc0-2020-09-14), the import/require statements now need to be `@cucumber/cucumber`

The RC for v7 was just released today.

**Comment by aslakhellesoy** [comment]
Just a heads up that we (the cucumber core team) intend to implement common formatters (such as `pretty`) as libraries in the [cucumber/cucumber monorepo](https://github.com/cucumber/cucumber).

By doing this we can have a shared test suite across different implementations. Here is a simple example: https://github.com/cucumber/cucumber/tree/master/demo-formatter

Here is a slightly more complicated one: https://github.com/cucumber/cucumber/tree/master/html-formatter

If you have energy to maintain a pretty formatter, I'd prefer if you wanted to join efforts on that instead.

**Comment by kozhevnikov** [comment]
I've tried updating to 7 and `@cucumber/cucumber` but it doesn't seem to be printing anything anymore. Do I understand it correctly that the event protocol has been completely removed in favour of `cucumber-message` so the formatter needs to be rewritten from scratch?

When are you planning to release the pretty formatter? I'll add it to the README and archive this project in favour of the native implementation.

**Comment by mattwynne** [comment]
> Do I understand it correctly that the event protocol has been completely removed in favour of cucumber-message

@kozhevnikov I'm not as close to the v7 implementation as Aslak, but that's my understanding, yes.

> so the formatter needs to be rewritten from scratch?

I had a quick look, and it struck me we could probably build a little adapter that turns the`cucumber-message` protocol into something similar enough to the event protocol that we could get this working again quite quickly.

> When are you planning to release the pretty formatter?

As far as I'm aware this is more of a strategic aim than something that's in progress right now. For me, it might be more pragmatic to get this one working again, and then see if we can extract something from it as a basis for a starting point for a more generic one.

**Comment by jbpros** [comment]
#16 and #17 are candidate fixes for this.

**Comment by jbpros** [comment]
The Cucumber 7-compatible pretty formatter has been published: https://www.npmjs.com/package/@cucumber/pretty-formatter. See https://github.com/kozhevnikov/cucumber-pretty/pull/17#issuecomment-756430339 and https://github.com/jbpros/cucumber-pretty-formatter/blob/master/CHANGELOG.md#v100-alpha0 for more info.

**Comment by satabdisikdar** [comment]
When do we get an update for this issue? cucumber-pretty supporting @cucumber/cucumber (Cucumber 7) ?

**Comment by jbpros** [comment]
@satabdisikdar See [my comment](https://github.com/kozhevnikov/cucumber-pretty/issues/14#issuecomment-756431608) right before yours.

**Comment by kozhevnikov** [comment]
@satabdisikdar please use official pretty formatter for Cucumber 7 and beyond. This project has served its purpose and there is no reason to have a competing implementation. It'll remain open until Cucumber 6 users migrate over to 7 and then will be archived.

https://www.npmjs.com/package/@cucumber/pretty-formatter

**Comment by jbpros** [comment]
@kozhevnikov should we close this ticket here?

**Comment by kozhevnikov** [comment]
Leave it. I should really update the readme and put upper limit on the peer version supported.

**Comment by satabdisikdar** [comment]
@kozhevnikov Thank you for the quick response but I was still seeing the issue- 
`Error: Cannot find module 'node_modules/@cucumber/pretty-formatter'`
Require stack:- `/home/abc/Documents/xyz/FY_web_test/web/test/index.js`
dependencies:
![Screenshot from 2021-06-16 18-16-51](https://user-images.githubusercontent.com/47587259/122221601-0c9b7980-cecf-11eb-811b-9d4345fbbe94.png)

**Comment by kozhevnikov** [comment]
@satabdisikdar you should ask maintainers of that package.

https://github.com/jbpros/cucumber-pretty-formatter
