### ISSUE TITLE
[doc] wrong path to cucumber in the .gif example

### ISSUE THREAD

**Issue by fmagaldea** [kozhevnikov/cucumber-pretty#2]
Binary "/node_modules/.bin/cucumber.js" doesn't exists anymore as cucumber-js v4, see https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md

**Comment by kozhevnikov** [comment]
It is meant for illustration purposes only, not as documentation. I rerecord it whenever pretty output changes significantly.
