### ISSUE TITLE
Not showing descriptions under "Feature"

### ISSUE THREAD

**Issue by xliiauo** [kozhevnikov/cucumber-pretty#5]
Hi, I was trying to use your formatter in my project. But seems on either mine or your project, the lines of descriptions under the "Feature" is not showing as expected. Please could you have a look. Many thanks :)
<img width="327" alt="screenshot" src="https://user-images.githubusercontent.com/9721723/44004013-a53b764a-9e53-11e8-9531-278b51f55436.png">
<img width="879" alt="screenshot" src="https://user-images.githubusercontent.com/9721723/44004015-b609ca58-9e53-11e8-9bb6-47347415376f.png">

**Comment by kozhevnikov** [comment]
Do you want it to be displayed? I found it to be unnecessary and noisy in output so I commented it out.

https://github.com/kozhevnikov/cucumber-pretty/blob/master/index.js#L58

**Comment by xliiauo** [comment]
It would be nice to have. If it's written in the features, why not show them in the test outputs. 😄

**Comment by kozhevnikov** [comment]
Added `descriptionEnabled` option in 1.5.0 similar to `colorsEnabled` one.
