### ISSUE TITLE
Is it compatible with protractor?

### ISSUE THREAD

**Issue by djom202** [kozhevnikov/cucumber-pretty#7]
I'm using protractor right now, but cucumber-js deprecated this `pretty` option, so I found this tools, I would like to know if I can use with protractor o I can't do it.

Thanks so much.

**Comment by kozhevnikov** [comment]
I believe it should be. Check Protractor docs on how to add Cucumber arguments.

**Comment by kozhevnikov** [comment]
https://medium.com/@fertavora/how-to-run-cucumber-tests-in-protractor-b1aec7826ea#cb05

**Comment by Marketionist** [comment]
@djom20 `cucumber-pretty` works ok with `protractor` (here is the example of how to enable it in configs https://github.com/Marketionist/protractor-cucumber-steps/blob/master/tests/protractor.conf.js#L51)
