### ISSUE TITLE
Release the package in NPM

### ISSUE THREAD

**Issue by mgonnet** [kozhevnikov/cucumber-pretty#8]
Hi!

We have been using your tool in our project for a while. I came to the repo because I was needing the option of disable the colors and wanted to see if I could do it myself. But I just saw that you already did it some weeks ago. Good work! This formatter has been very useful.

So.. I wanted to ask, could you update npm with the new code? Sorry for the inconvenience, and if you need some code contribution, I would be glad to help.

**Comment by kozhevnikov** [comment]
Not sure what you mean, npm has the latest master as of version 1.5.0.

The `colorsEnabled` option is actually default Cucumber format option, see below.

https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#colors

**Comment by mgonnet** [comment]
Sorry, I missed the npm update, embarrased.
